#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication decomposePar -copyZero

runParallel renumberMesh -overwrite

runParallel pimpleFoam

runApplication reconstructParMesh -constant -mergeTol 1e-6

runApplication reconstructPar

#------------------------------------------------------------------------------
